title = '夜明けと蛍'
artist = 'ナブナ'
track = '夜明けと蛍.ogg'
bpm = 100
offset = 1.20
demo = [ 24.36, 30.44 ]
level = [ 1, 3, 6, 9 ]

easy = '''
    r0, b1,
    p3, g4;
    b1, g6;
    pb2, yg5;
    r0;
    g1;
    p3,,,y2;
    ;
    y6;
'''

normal = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''

hard = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''

lunatic = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''