title = '夜明けと蛍'
artist = 'ナブナ'
track = '夜明けと蛍.ogg'
bpm = 138
offset = 1.20
demo = [ 24.36, 30.44 ]
level = [ 1, 3, 6, 9 ]

easy = '''
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
    b1, g2, p5, y6;
'''

normal = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''

hard = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''

lunatic = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''