title = '夜明けと蛍'
artist = 'ナブナ'
track = '夜明けと蛍.ogg'
bpm = 138
offset = 1.20
demo = [ 24.36, 30.44 ]
level = [ 1, 3, 6, 9 ]

easy = '''
    1, 2, 3, 4, 5;
    1, 2, 3, 4, 5;
    1, 2, 3, 4, 5;
    1, 2, 3, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
    1, 2, 4, 5;
'''

normal = '''
    1,2,4,5;
    12,54,21,45;
    $bpm = 120
    1-5,21-45;
    [1,]2;
    {4,}5;
'''

hard = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''

lunatic = '''
    r0,rb1;
    r1-p5;
    %^r1;
    %|;
    %_p3;
    $^b1,$|r2,$_p3;
'''